[package]
name = "sherby-pace-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peak_alloc = "0.2.0"
petgraph = "0.6.4"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
